"""French disease labels and short agronomic information for the Streamlit UI."""

from __future__ import annotations

SPECIES_LABELS = {
    "tomato": "Tomate",
    "apple": "Pommier",
    "grape": "Vigne",
    "corn": "Maïs",
    "potato": "Pomme de terre",
    "pepper": "Poivron",
    "strawberry": "Fraisier",
}

DISEASE_LABELS = {
    "Apple_Scab": "Tavelure du pommier",
    "Black_Rot": "Pourriture noire",
    "Cedar_Apple_Rust": "Rouille du cèdre du pommier",
    "Cercospora_Leaf_Spot": "Cercosporiose / tache grise",
    "Common_Rust": "Rouille commune",
    "Northern_Leaf_Blight": "Brûlure septentrionale des feuilles",
    "Esca_Black_Measles": "Esca / maladie des taches noires",
    "Leaf_Blight": "Brûlure des feuilles",
    "Bacterial_Spot": "Tache bactérienne",
    "Early_Blight": "Mildiou précoce / alternariose",
    "Late_Blight": "Mildiou tardif",
    "Leaf_Scorch": "Brûlure des feuilles",
    "Leaf_Mold": "Moisissure des feuilles",
    "Mosaic_Virus": "Virus de la mosaïque de la tomate",
    "Septoria_Leaf_Spot": "Septoriose",
    "Spider_Mites": "Acariens tétranyques",
    "Target_Spot": "Tache cible",
    "Yellow_Leaf_Curl_Virus": "Virus de l'enroulement jaune des feuilles",
    "Healthy": "Feuille saine",
}

DISEASE_INFO = {
    ("apple", "Apple_Scab"): {
        "title": "Tavelure du pommier",
        "english": "Apple scab",
        "url": "https://fr.wikipedia.org/wiki/Tavelure_du_pommier",
        "agent": "Venturia inaequalis, champignon qui infecte feuilles et fruits.",
        "curative": "Retirer les organes très atteints ; utiliser une protection fongicide en période à risque.",
        "preventive": "Variétés résistantes, ramassage des feuilles, taille pour aérer, prévention au printemps.",
        "season_gravity": "Printemps et début d'été ; gravité élevée.",
    },
    ("apple", "Black_Rot"): {
        "title": "Pourriture noire du pommier",
        "english": "Apple black rot",
        "url": "https://en.wikipedia.org/wiki/Botryosphaeria_obtusa",
        "agent": "Botryosphaeria obtusa, champignon associé aux taches foliaires et chancres.",
        "curative": "Supprimer fruits momifiés, rameaux chancrés et bois mort ; fongicide si forte pression.",
        "preventive": "Hygiène du verger, taille du bois atteint, bonne aération et limitation des blessures.",
        "season_gravity": "Printemps à été ; gravité moyenne à élevée.",
    },
    ("apple", "Cedar_Apple_Rust"): {
        "title": "Rouille du cèdre du pommier",
        "english": "Cedar apple rust",
        "url": "https://en.wikipedia.org/wiki/Gymnosporangium_juniperi-virginianae",
        "agent": "Gymnosporangium juniperi-virginianae, rouille alternant pommiers et genévriers.",
        "curative": "Retirer les parties très atteintes ; protéger le pommier au printemps si risque élevé.",
        "preventive": "Cultivars résistants, gestion des genévriers proches et traitements préventifs au printemps.",
        "season_gravity": "Printemps et début d'été ; gravité moyenne, élevée localement.",
    },
    ("corn", "Cercospora_Leaf_Spot"): {
        "title": "Cercosporiose / tache grise du maïs",
        "english": "Gray leaf spot",
        "url": "https://extension.umn.edu/corn-pest-management/gray-leaf-spot-corn",
        "agent": "Cercospora zeae-maydis, champignon favorisé par chaleur et forte humidité.",
        "curative": "Fongicide foliaire si le risque économique est atteint ; les lésions installées ne guérissent pas.",
        "preventive": "Hybrides résistants, rotation, gestion des résidus et surveillance en conditions humides.",
        "season_gravity": "Été chaud et humide ; gravité élevée.",
    },
    ("corn", "Common_Rust"): {
        "title": "Rouille commune du maïs",
        "english": "Common rust",
        "url": "https://en.wikipedia.org/wiki/Puccinia_sorghi",
        "agent": "Puccinia sorghi, champignon responsable de pustules de rouille.",
        "curative": "Fongicide possible si infection précoce et forte pression sur hybride sensible.",
        "preventive": "Hybrides moins sensibles, surveillance et intervention seulement si risque réel.",
        "season_gravity": "Été frais à modéré et humide ; gravité moyenne.",
    },
    ("corn", "Northern_Leaf_Blight"): {
        "title": "Brûlure septentrionale des feuilles",
        "english": "Northern corn leaf blight",
        "url": "https://fr.wikipedia.org/wiki/Helminthosporiose_du_ma%C3%AFs",
        "agent": "Setosphaeria turcica / Exserohilum turcicum.",
        "curative": "Fongicide foliaire pour freiner l'extension si les feuilles hautes sont menacées.",
        "preventive": "Hybrides résistants, rotation avec non-graminées et gestion des résidus.",
        "season_gravity": "Été humide à températures modérées ; gravité élevée.",
    },
    ("grape", "Black_Rot"): {
        "title": "Pourriture noire de la vigne",
        "english": "Grape black rot",
        "url": "https://fr.wikipedia.org/wiki/Black_rot",
        "agent": "Guignardia bidwellii, champignon destructeur sur feuilles et grappes.",
        "curative": "Supprimer grappes momifiées et organes très atteints ; protéger les nouveaux tissus.",
        "preventive": "Assainissement, aération du couvert et programme préventif par temps chaud et humide.",
        "season_gravity": "Printemps à été ; gravité élevée.",
    },
    ("grape", "Esca_Black_Measles"): {
        "title": "Esca / maladie des taches noires",
        "english": "Black measles",
        "url": "https://fr.wikipedia.org/wiki/Esca",
        "agent": "Complexe de champignons des maladies du bois de la vigne.",
        "curative": "Pas de vrai curatif fongicide ; curetage, reformation ou remplacement des ceps atteints.",
        "preventive": "Protéger les plaies de taille, tailler par temps sec et limiter les grosses plaies.",
        "season_gravity": "Symptômes surtout en été ; gravité élevée.",
    },
    ("grape", "Leaf_Blight"): {
        "title": "Brûlure des feuilles de la vigne",
        "english": "Isariopsis leaf spot",
        "url": "https://en.wikipedia.org/wiki/Pseudocercospora_vitis",
        "agent": "Pseudocercospora vitis, champignon foliaire.",
        "curative": "Retirer les feuilles très atteintes ; fongicide si la pression augmente.",
        "preventive": "Aération du feuillage, palissage, effeuillage raisonné et assainissement.",
        "season_gravity": "Saison de croissance, souvent fin de saison ; gravité faible à moyenne.",
    },
    ("pepper", "Bacterial_Spot"): {
        "title": "Tache bactérienne du poivron",
        "english": "Bacterial spot",
        "url": "https://ipm.ucanr.edu/agriculture/peppers/bacterial-spot/",
        "agent": "Complexe de bactéries Xanthomonas.",
        "curative": "Pas de guérison des tissus infectés ; retirer les foyers et limiter la propagation.",
        "preventive": "Plants sains, rotation, irrigation au goutte-à-goutte et limitation du feuillage mouillé.",
        "season_gravity": "Saison chaude et humide ; gravité élevée si introduction précoce.",
    },
    ("potato", "Early_Blight"): {
        "title": "Mildiou précoce / alternariose",
        "english": "Early blight",
        "url": "https://fr.wikipedia.org/wiki/Alternaria_solani",
        "agent": "Alternaria solani, champignon favorisé par stress et humidité.",
        "curative": "Retirer les feuilles très atteintes ; fongicide anti-alternariose si risque confirmé.",
        "preventive": "Rotation, destruction des résidus, fertilisation équilibrée et variétés moins sensibles.",
        "season_gravity": "Été ou période chaude ; gravité moyenne à élevée.",
    },
    ("potato", "Late_Blight"): {
        "title": "Mildiou tardif de la pomme de terre",
        "english": "Late blight",
        "url": "https://fr.wikipedia.org/wiki/Mildiou_de_la_pomme_de_terre",
        "agent": "Phytophthora infestans, oomycète à propagation rapide.",
        "curative": "Détruire rapidement les foyers ; traitements anti-oomycètes adaptés selon le risque.",
        "preventive": "Plants sains, surveillance météo, prévention précoce et bonne aération.",
        "season_gravity": "Temps frais à doux et humide ; gravité très élevée.",
    },
    ("strawberry", "Leaf_Scorch"): {
        "title": "Brûlure des feuilles du fraisier",
        "english": "Leaf scorch",
        "url": "https://en.wikipedia.org/wiki/Diplocarpon_earlianum",
        "agent": "Diplocarpon earlianum, champignon foliaire.",
        "curative": "Enlever feuilles et débris atteints ; fongicide si la pression devient forte.",
        "preventive": "Plants sains, espacement, éviter l'aspersion, rotation et assainissement.",
        "season_gravity": "Printemps humide à été ; gravité moyenne.",
    },
    ("tomato", "Bacterial_Spot"): {
        "title": "Tache bactérienne de la tomate",
        "english": "Bacterial spot",
        "url": "https://ipm.ucanr.edu/agriculture/tomato/bacterial-spot/",
        "agent": "Complexe de bactéries Xanthomonas.",
        "curative": "Pas de cure des tissus infectés ; suppression des foyers et protection de couverture.",
        "preventive": "Semences/plants sains, rotation, arrosage au pied et hygiène stricte.",
        "season_gravity": "Chaud et humide ; gravité élevée.",
    },
    ("tomato", "Early_Blight"): {
        "title": "Mildiou précoce / alternariose de la tomate",
        "english": "Early blight",
        "url": "https://fr.wikipedia.org/wiki/Alternaria_solani",
        "agent": "Alternaria solani, parfois Alternaria tomatophila sur tomate.",
        "curative": "Supprimer les feuilles basses très atteintes ; fongicide si la maladie progresse.",
        "preventive": "Rotation, tuteurage, paillage, arrosage au pied et bonne circulation d'air.",
        "season_gravity": "Temps modéré à chaud avec humidité foliaire ; gravité moyenne à élevée.",
    },
    ("tomato", "Late_Blight"): {
        "title": "Mildiou tardif de la tomate",
        "english": "Late blight",
        "url": "https://ipm.ucanr.edu/agriculture/tomato/late-blight/",
        "agent": "Phytophthora infestans.",
        "curative": "Détruire rapidement les plants très atteints ; traiter très tôt en période à risque.",
        "preventive": "Plants sains, aération, surveillance météo et prévention précoce.",
        "season_gravity": "Temps frais à doux et humide ; gravité très élevée.",
    },
    ("tomato", "Leaf_Mold"): {
        "title": "Moisissure des feuilles de la tomate",
        "english": "Tomato leaf mold",
        "url": "https://extension.umn.edu/disease-management/tomato-leaf-mold",
        "agent": "Passalora fulva, anciennement Fulvia fulva ou Cladosporium fulvum.",
        "curative": "Retirer les feuilles atteintes, réduire l'humidité et utiliser un fongicide si besoin.",
        "preventive": "Ventilation, éviter la condensation, arrosage au pied et variétés résistantes.",
        "season_gravity": "Surtout sous serre ou forte humidité ; gravité moyenne à élevée.",
    },
    ("tomato", "Mosaic_Virus"): {
        "title": "Virus de la mosaïque de la tomate",
        "english": "Tomato mosaic virus",
        "url": "https://fr.wikipedia.org/wiki/Virus_de_la_mosa%C3%AFque_de_la_tomate",
        "agent": "Tomato mosaic virus, virus transmis surtout mécaniquement.",
        "curative": "Aucun curatif ; éliminer les plants infectés et désinfecter outils et supports.",
        "preventive": "Semences saines, variétés résistantes et hygiène stricte.",
        "season_gravity": "Toute la saison si introduit ; gravité élevée.",
    },
    ("tomato", "Septoria_Leaf_Spot"): {
        "title": "Septoriose de la tomate",
        "english": "Septoria leaf spot",
        "url": "https://fr.wikipedia.org/wiki/Septoria_lycopersici",
        "agent": "Septoria lycopersici, champignon foliaire.",
        "curative": "Supprimer les feuilles atteintes ; fongicide de protection si la pression augmente.",
        "preventive": "Rotation, paillage, tuteurage, arrosage au pied et retrait des débris.",
        "season_gravity": "Temps chaud à modéré et humide ; gravité moyenne à élevée.",
    },
    ("tomato", "Spider_Mites"): {
        "title": "Acariens tétranyques",
        "english": "Two-spotted spider mites",
        "url": "https://en.wikipedia.org/wiki/Tetranychus_urticae",
        "agent": "Tetranychus urticae, acarien favorisé par chaleur et sécheresse.",
        "curative": "Doucher le dessous des feuilles, savon insecticide, huile horticole ou acaricide si besoin.",
        "preventive": "Surveiller tôt, limiter le stress hydrique, réduire la poussière et préserver les auxiliaires.",
        "season_gravity": "Temps chaud et sec ; gravité moyenne, élevée en serre ou canicule.",
    },
    ("tomato", "Target_Spot"): {
        "title": "Tache cible de la tomate",
        "english": "Target spot",
        "url": "https://en.wikipedia.org/wiki/List_of_tomato_diseases",
        "agent": "Corynespora cassiicola.",
        "curative": "Retirer les feuilles très atteintes ; fongicide si la maladie progresse.",
        "preventive": "Rotation, destruction des résidus, espacement, taille et réduction de l'humidité foliaire.",
        "season_gravity": "Humidité élevée et températures modérées à chaudes ; gravité moyenne à élevée.",
    },
    ("tomato", "Yellow_Leaf_Curl_Virus"): {
        "title": "Virus de l'enroulement jaune des feuilles",
        "english": "Tomato yellow leaf curl virus",
        "url": "https://fr.wikipedia.org/wiki/Virus_des_feuilles_jaunes_en_cuill%C3%A8re_de_la_tomate",
        "agent": "Tomato yellow leaf curl virus, transmis surtout par Bemisia tabaci.",
        "curative": "Aucun curatif ; arracher les foyers limités et contrôler fortement les aleurodes.",
        "preventive": "Variétés tolérantes, contrôle du vecteur, filets, élimination des réservoirs adventices.",
        "season_gravity": "Saison chaude et forte pression d'aleurodes ; gravité très élevée.",
    },
}
